name: PHP Tests

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.0, 8.1, 8.2]

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - run: composer install
      - run: vendor/bin/parallel-lint src tests
      - run: vendor/bin/phpcs src tests --standard=ruleset.xml -d memory_limit=512M
      - run: vendor/bin/phpstan analyse -l 9 -c phpstan.neon src tests
      - run: vendor/bin/tester -p php tests/ -s -c tests/php.ini